{
 "title": "ICOS Agent View",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "icos_telemetry_db", "label": "ICOS Telemetry DB", "query": "prometheus" },
   {
    "name": "agent_id",
    "label": "ICOS Agent Id",
    "query": {
     "query": "label_values(tlum_host_info,icos_agent_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ICOS Hosts",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "tlum_host_info{icos_agent_id=\"$agent_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "tlum_host_info{icos_agent_id=\"$agent_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Agent Characteristics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Peripherals",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "label_replace(node_mounted{icos_agent_id=\"$agent_id\"}, \"k8s_node_name\", \"$1\", \"node_name\", \"(.+)\") * on(k8s_node_name) group_left(icos_host_name) tlum_host_info{icos_agent_id=\"$agent_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Security (SCA Score)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tlum_host_info{icos_agent_id=\"$agent_id\"} * on(hostname) group_right(id, icos_host_name) label_replace(label_replace(SCA_score, \"ip\", \"$1\", \"agent_ip\", \"(.+)\"), \"hostname\", \"$1\", \"agent_hostname\", \"(.+)\")",
     "legendFormat": "{{icos_host_name}}"
    }
   ]
  },
  {
   "title": "Security (Vulnerabilities)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tlum_host_info{icos_agent_id=\"$agent_id\"} * on(hostname) group_right(id, icos_host_name) label_replace(label_replace(vulnerabilities, \"ip\", \"$1\", \"agent_ip\", \"(.+)\"), \"hostname\", \"$1\", \"agent_hostname\", \"(.+)\")",
     "legendFormat": "{{icos_host_name}} {{severity}}"
    }
   ]
  },
  {
   "title": "Agent Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true
  },
  {
   "title": "Hosts CPU Utilization Ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without (cpu) (1 - rate(node_cpu_seconds_total{icos_agent_id=\"$agent_id\", mode=\"idle\"}[2m]))",
     "legendFormat": "{{icos_host_name}}"
    }
   ]
  },
  {
   "title": "Hosts Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{icos_agent_id=\"$agent_id\"}",
     "legendFormat": "{{icos_host_name}}"
    }
   ]
  },
  {
   "title": "Hosts Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{icos_agent_id=\"$agent_id\"} - node_memory_MemFree_bytes{icos_agent_id=\"$agent_id\"} - (node_memory_Cached_bytes{icos_agent_id=\"$agent_id\"} + node_memory_Buffers_bytes{icos_agent_id=\"$agent_id\"} + node_memory_SReclaimable_bytes{icos_agent_id=\"$agent_id\"})",
     "legendFormat": "{{icos_host_name}}"
    }
   ]
  },
  {
   "title": "Disk Space Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{icos_agent_id=\"$agent_id\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{icos_agent_id=\"$agent_id\",device!~'rootfs'})",
     "legendFormat": "{{icos_host_name}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Power Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "scaph_host_power_microwatts{icos_agent_id=\"$agent_id\"} / 1000",
     "legendFormat": "{{icos_host_name}}"
    }
   ]
  },
  { "title": "ICOS Apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Running Workloads",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by (name, icos_host_name, icos_app_name, icos_app_component, icos_app_instance) (tlum_workload_info{icos_agent_id=\"$agent_id\", icos_app_name=~\"(.+)\", icos_app_component=~\"(.+)\", icos_app_instance=~\"(.+)\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Policies Enforced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "plm_policy_enforced{icos_agent_id=\"$agent_id\"}",
     "legendFormat": "node - {{name}}"
    },
    {
     "expr": "plm_policy_enforced * on(icos_app_instance) group_left tlum_workload_info{icos_agent_id=\"$agent_id\", icos_app_name=~\"(.+)\", icos_app_component=~\"(.+)\", icos_app_instance=~\"(.+)\"}",
     "legendFormat": "app - {{name}}"
    }
   ]
  }
 ]
}